### ISSUE TITLE
Clicking on the green dot to maximize the windows crashes the app

### ISSUE THREAD

**Issue by pjosuah** [App-Fair/App#7]
Litterally the title.

Currently on the latest version 0.8.90 (844).

macOS Montery 12.0.1 on MBP M1.

**Comment by marcprux** [comment]
It works for me without crashing on an M1 MPB, but I'm running macOS 12.5. There have been a lot of SwiftUI bugs fixed since 12.0.1, so I wonder if updating the OS might fix the problem.

Otherwise, do you see a problem report dialog when it crashes? If so, could you copy and paste the crash log into this issue?

**Comment by marcprux** [comment]
Cannot reproduce, so I am closing the issue. Please update this issue if you have more information to share.
